#!/usr/bin/env python3
"""Fetch Triton kernel functions from vLLM and write kernels/<name>/original.py.

Reads kernels.json for the mapping, downloads each vLLM source file,
extracts the @triton.jit kernel function via AST parsing, and writes
(or overwrites) original.py entirely. Wrapper functions live in a
separate wrapper.py and are not touched by this script.

Usage:
    python scripts/fetch_originals.py          # fetch all kernels
    python scripts/fetch_originals.py rms_norm  # fetch one kernel
    python scripts/fetch_originals.py --diff    # diff-only mode (no writes)
"""

import ast
import base64
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KERNELS_JSON = ROOT / "kernels.json"
KERNELS_DIR = ROOT / "kernels"


def load_registry():
    with open(KERNELS_JSON) as f:
        return json.load(f)


def fetch_vllm_file(repo: str, commit: str, vllm_path: str) -> str:
    """Download a file from GitHub using gh CLI."""
    result = subprocess.run(
        ["gh", "api", f"repos/{repo}/contents/{vllm_path}?ref={commit}",
         "--jq", ".content"],
        capture_output=True, text=True, check=True,
    )
    return base64.b64decode(result.stdout.strip()).decode()


def extract_triton_kernel(source: str, func_name: str) -> str:
    """Extract a @triton.jit function (with decorators) from Python source."""
    tree = ast.parse(source)
    lines = source.split("\n")
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == func_name:
            start = node.lineno - 1
            if node.decorator_list:
                start = node.decorator_list[0].lineno - 1
            end = node.end_lineno
            return "\n".join(lines[start:end])
    raise ValueError(f"Function {func_name!r} not found in source")


def make_header(vllm_path: str, func_name: str,
                repo: str, commit: str) -> str:
    url = f"https://github.com/{repo}/blob/{commit}/{vllm_path}"
    return (
        f"# SPDX-License-Identifier: Apache-2.0\n"
        f"# SPDX-FileCopyrightText: Copyright contributors to the vLLM project\n"
        f"#\n"
        f"# Kernel function extracted verbatim from vLLM.\n"
        f"# Source: {url}\n"
        f"# Function: {func_name}\n"
        f"# Commit: {commit}\n"
        f"#\n"
        f"# Do not edit the kernel function below — it is auto-generated by\n"
        f"# scripts/fetch_originals.py from kernels.json.\n"
    )


IMPORTS = (
    "\nimport math\n"
    "\nimport torch\n"
    "import triton\n"
    "import triton.language as tl\n"
)


def process_kernel(kernel_name: str, info: dict, repo: str, commit: str,
                   diff_only: bool = False) -> bool:
    """Process one kernel. Returns True if content changed."""
    vllm_path = info["vllm_file"]
    func_name = info["kernel_function"]
    original_py = KERNELS_DIR / kernel_name / "original.py"

    print(f"  Fetching {vllm_path} :: {func_name}")
    source = fetch_vllm_file(repo, commit, vllm_path)
    kernel_code = extract_triton_kernel(source, func_name)

    header = make_header(vllm_path, func_name, repo, commit)
    new_content = header + IMPORTS + "\n\n" + kernel_code + "\n"

    if original_py.exists():
        old_content = original_py.read_text()
        if old_content == new_content:
            print(f"  {kernel_name}: unchanged")
            return False

    if diff_only:
        print(f"  {kernel_name}: DIFFERS (use without --diff to update)")
        return True

    original_py.parent.mkdir(parents=True, exist_ok=True)
    original_py.write_text(new_content)
    print(f"  {kernel_name}: written to {original_py}")
    return True


def main():
    diff_only = "--diff" in sys.argv
    targets = [a for a in sys.argv[1:] if not a.startswith("-")]

    registry = load_registry()
    repo = registry["repo"]
    commit = registry["commit"]
    kernels = registry["kernels"]

    if targets:
        for t in targets:
            if t not in kernels:
                print(f"ERROR: unknown kernel {t!r}. Available: {', '.join(kernels)}")
                sys.exit(1)
        selected = {k: kernels[k] for k in targets}
    else:
        selected = kernels

    changed = 0
    for name, info in selected.items():
        print(f"[{name}]")
        try:
            if process_kernel(name, info, repo, commit, diff_only):
                changed += 1
        except Exception as e:
            print(f"  ERROR: {e}")
            changed += 1

    print(f"\n{'Diff' if diff_only else 'Done'}: {changed} kernel(s) {'differ' if diff_only else 'updated'}, "
          f"{len(selected) - changed} unchanged")


if __name__ == "__main__":
    main()
